plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fctv.player8k'
    compileSdk 36

    defaultConfig {
        applicationId 'com.fctv.player8k'
        minSdk 23
        targetSdk 36
        versionCode 3
        versionName '1.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
}
